dental_app/dental_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patient_management.urls'))
]

dental_app/patient_management/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('main/', views.main, name='main'),
    path('add-patient/', views.AddPatientFormView.as_view(), name='add-patient'),
    path('patient-details/<int:patient_id>', views.edit_patient, name='patient-details'),
    path('delete-financial/<int:financial_form_id>', views.delete_financial, name='delete-financial'),
    path('calendar/', include('appointment_calendar.urls'), name='calendar'),
    path('backup/', views.backup_data, name='backup'),
    path('restore/', views.restore_data, name='restore'),
    path('', views.logout_user, name='logout')
]

dental_app/patient_management/models.py
from django.db import models


# Create your models here.

class Patient(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100, blank=True)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=100, blank=True)
    mobile_phone = models.CharField(max_length=100)
    amka = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    occupation = models.CharField(max_length=100, blank=True)
    previous_dentist_visit = models.CharField(max_length=100, blank=True)
    found_in = models.CharField(max_length=100, blank=True)
    notes = models.CharField(max_length=5000, null=True, blank=True)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.full_name()


class MedicalHistory(models.Model):
    aids = models.BooleanField(default=False)
    anemia = models.BooleanField(default=False)
    arthritis = models.BooleanField(default=False)
    artificial_joint = models.BooleanField(default=False)
    asthma = models.BooleanField(default=False)
    blood_disease = models.BooleanField(default=False)
    breathing_problem = models.BooleanField(default=False)
    cancer = models.BooleanField(default=False)
    chemotherapy = models.BooleanField(default=False)
    cortisone_medicine = models.BooleanField(default=False)
    diabetes = models.BooleanField(default=False)
    excessive_bleeding = models.BooleanField(default=False)
    hepatitis_A = models.BooleanField(default=False)
    hepatitis_B_or_C = models.BooleanField(default=False)
    hemophilia = models.BooleanField(default=False)
    high_blood_pressure = models.BooleanField(default=False)
    high_cholesterol = models.BooleanField(default=False)
    hyperthyroidism = models.BooleanField(default=False)
    hypothyroidism = models.BooleanField(default=False)
    low_blood_pressure = models.BooleanField(default=False)
    osteoporosis = models.BooleanField(default=False)
    pain_in_jaw_joints = models.BooleanField(default=False)
    parathyroid_disease = models.BooleanField(default=False)
    radiation_treatments = models.BooleanField(default=False)
    rheumatoid_arthritis = models.BooleanField(default=False)
    thyroid_disease = models.BooleanField(default=False)
    medicine = models.CharField(max_length=5000, null=True, blank=True)
    allergies = models.CharField(max_length=5000, null=True, blank=True)
    notes = models.CharField(max_length=5000, null=True, blank=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)


class DentalHistory(models.Model):
    complications_past_treatment = models.BooleanField(default=False)
    reactions_anesthesia = models.BooleanField(default=False)
    teeth_removed = models.BooleanField(default=False)
    orthodontic_treatment = models.BooleanField(default=False)
    gums_bleed = models.BooleanField(default=False)
    gum_disease = models.BooleanField(default=False)
    bone_loss_around_teeth = models.BooleanField(default=False)
    mouth_unpleasant_taste_smell = models.BooleanField(default=False)
    family_history_periodontal_gum_disease = models.BooleanField(default=False)
    gum_recession = models.BooleanField(default=False)
    teeth_become_loose = models.BooleanField(default=False)
    cavities_past_three_years = models.BooleanField(default=False)
    teeth_sensitive_to_hot_cold = models.BooleanField(default=False)
    food_caught_between_teeth = models.BooleanField(default=False)
    ever_broken_chipped_cracked_any_teeth = models.BooleanField(default=False)
    problems_with_jaw_joint = models.BooleanField(default=False)
    teeth_changed_in_last_five_years = models.BooleanField(default=False)
    clench_teeth_during_day_night = models.BooleanField(default=False)
    wear_or_worn_bite_appliance = models.BooleanField(default=False)
    ever_whitened_bleached_teeth = models.BooleanField(default=False)
    main_complaint = models.CharField(max_length=500, null=True, blank=True)
    notes = models.CharField(max_length=5000, null=True, blank=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)


class TreatmentPlan(models.Model):
    treatment_plan_description = models.CharField(max_length=500, blank=False)
    treatment_plan_start_date = models.DateField(blank=True, null=True)
    treatment_plan_end_date = models.DateField(blank=True, null=True)
    treatment_plan_notes = models.CharField(max_length=5000, blank=True, null=True)
    total_cost = models.FloatField(default=0.0, blank=True, null=True)
    treatment_plan_balance = models.FloatField(default=0.0, blank=True, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)


class Odontogram(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    tooth_11 = models.CharField(max_length=200, default=None, null=True)
    tooth_12 = models.CharField(max_length=200, default=None, null=True)
    tooth_13 = models.CharField(max_length=200, default=None, null=True)
    tooth_14 = models.CharField(max_length=200, default=None, null=True)
    tooth_15 = models.CharField(max_length=200, default=None, null=True)
    tooth_16 = models.CharField(max_length=200, default=None, null=True)
    tooth_17 = models.CharField(max_length=200, default=None, null=True)
    tooth_18 = models.CharField(max_length=200, default=None, null=True)

    tooth_21 = models.CharField(max_length=200, default=None, null=True)
    tooth_22 = models.CharField(max_length=200, default=None, null=True)
    tooth_23 = models.CharField(max_length=200, default=None, null=True)
    tooth_24 = models.CharField(max_length=200, default=None, null=True)
    tooth_25 = models.CharField(max_length=200, default=None, null=True)
    tooth_26 = models.CharField(max_length=200, default=None, null=True)
    tooth_27 = models.CharField(max_length=200, default=None, null=True)
    tooth_28 = models.CharField(max_length=200, default=None, null=True)

    tooth_31 = models.CharField(max_length=200, default=None, null=True)
    tooth_32 = models.CharField(max_length=200, default=None, null=True)
    tooth_33 = models.CharField(max_length=200, default=None, null=True)
    tooth_34 = models.CharField(max_length=200, default=None, null=True)
    tooth_35 = models.CharField(max_length=200, default=None, null=True)
    tooth_36 = models.CharField(max_length=200, default=None, null=True)
    tooth_37 = models.CharField(max_length=200, default=None, null=True)
    tooth_38 = models.CharField(max_length=200, default=None, null=True)

    tooth_41 = models.CharField(max_length=200, default=None, null=True)
    tooth_42 = models.CharField(max_length=200, default=None, null=True)
    tooth_43 = models.CharField(max_length=200, default=None, null=True)
    tooth_44 = models.CharField(max_length=200, default=None, null=True)
    tooth_45 = models.CharField(max_length=200, default=None, null=True)
    tooth_46 = models.CharField(max_length=200, default=None, null=True)
    tooth_47 = models.CharField(max_length=200, default=None, null=True)
    tooth_48 = models.CharField(max_length=200, default=None, null=True)


class Periodontogram(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    perio_tooth_11 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_12 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_13 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_14 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_15 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_16 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_17 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_18 = models.CharField(max_length=500, default=None, null=True)

    perio_tooth_21 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_22 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_23 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_24 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_25 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_26 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_27 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_28 = models.CharField(max_length=500, default=None, null=True)

    perio_tooth_31 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_32 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_33 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_34 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_35 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_36 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_37 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_38 = models.CharField(max_length=500, default=None, null=True)

    perio_tooth_41 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_42 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_43 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_44 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_45 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_46 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_47 = models.CharField(max_length=500, default=None, null=True)
    perio_tooth_48 = models.CharField(max_length=500, default=None, null=True)


class Financial(models.Model):
    transaction_amount = models.FloatField(null=True)

dental_app/patient_management/templates/patient_management/add-patient.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Add Patient
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'patient_management/styles.css' %}">
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
    {% csrf_token %}

    <form class="add-patient-form" action="/add-patient/" method="POST">
        {% csrf_token %}
        <div id="add-patient-header">
            <h3>Add patient</h3>
        </div>
            <div class="grid-container">
                <div class="grid-item"><p><label for="id_last_name"><span style="color:red; margin-right:6px; margin-left:-13px;">*</span>Last Name:</label></p></div>
                <div class="grid-item"><p>{{ form.last_name }}</p></div>
                <div class="grid-item"><p><label for="id_first_name"><span style="color:red; margin-right:6px; margin-left:-13px;">*</span>First Name:</label></p></div>
                <div class="grid-item"><p>{{ form.first_name }}</p></div>
                <div class="grid-item"><p><label for="id_address">Address:</label></p></div>
                <div class="grid-item"><p>{{ form.address }}</p></div>
                <div class="grid-item"><p><label for="id_email">Email:</label></p></div>
                <div class="grid-item"><p>{{ form.email }}</p></div>
                <div class="grid-item"><p><label for="id_phone">Phone:</label></p></div>
                <div class="grid-item"><p>{{ form.phone }}</p></div>
                <div class="grid-item"><p><label for="id_last_name"><span style="color:red; margin-right:6px; margin-left:-13px;">*</span>Mobile phone:</label></p></div>
                <div class="grid-item"><p>{{ form.mobile_phone }}</p></div>
                <div class="grid-item"><p><label for="id_amka">AMKA:</label></p></div>
                <div class="grid-item"><p>{{ form.amka }}</p></div>
                <div class="grid-item"><p><label for="id_date_of_birth">Date of Birth:</label></p></div>
                <div class="grid-item" id="date-of-birth"><p>{% render_field form.date_of_birth type="date" placeholder="dd/mm/yyyy" %}</p></div>
                <div class="grid-item"><p><label>Occupation:</label></p></div>
                <div class="grid-item"><p>{{ form.occupation }}</p></div>
                <div class="grid-item"><p><label>Previous visit:</label></p></div>
                <div class="grid-item"><p>{{ form.previous_dentist_visit }}</p></div>
                <div class="grid-item"><p><label>Found in:</label></p></div>
                <div class="grid-item"><p>{{ form.found_in }}</p></div>
                <div class="grid-item"><p></p></div>
                <div class="grid-item"><p></p></div>
                <div class="grid-item"><p><label for="id_notes">Notes:</label></p></div>
                <div class="grid-item"><p>{{ form.notes }}</p><div style="color:red; font-weight:bold; font-size:12px; margin-top:-1rem; margin-bottom:-1rem;">* Mandatory fields</div></div>
            </div>

        <br>
        <div class="add-form-button">
            <button type="submit" name="save" class="save-button">Save</button>
            <input type="reset" name="clear" class="reset-button" value="Reset">
        </div>
    </form>

    {% else %}

    <div class="login-promt">
        <body id="login-prompt-body">
            <form action="/login/">
                {% csrf_token %}
                <p class="login-prompt-message">You are not logged in</p>
                <button type="submit" name="login" class="btn btn-outline-primary" onclick="location.href='{% url 'login' %}'">Login</button>
            </form>
        </body>
    </div>

    {% endif %}

{% endblock %}

dental_app/patient_management/templates/patient_management/edit-patient.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Edit Patient
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'patient_management/styles.css' %}">
{% endblock %}

{% block content %}

    <div>
        <nav>
            <button type="submit" name="main-page" onclick="location.href='{% url 'main' %}'">Main page</button>
        </nav>
    </div>

    <form class="add-patient-form" action="" method="POST">
        {% csrf_token %}
        <h3>Edit patient</h3>

            <div class="grid-container">
                <div class="grid-item"><p><label for="id_last_name">Last Name:</label></p></div>
                <div class="grid-item"><p>{{ form.last_name }}</p></div>
                <div class="grid-item"><p><label for="id_first_name">First Name:</label></p></div>
                <div class="grid-item"><p>{{ form.first_name }}</p></div>
                <div class="grid-item"><p><label for="id_address">Address:</label></p></div>
                <div class="grid-item"><p>{{ form.address }}</p></div>
                <div class="grid-item"><p><label for="id_email">Email:</label></p></div>
                <div class="grid-item"><p>{{ form.email }}</p></div>
                <div class="grid-item"><p><label for="id_phone">Phone:</label></p></div>
                <div class="grid-item"><p>{{ form.phone }}</p></div>
                <div class="grid-item"><p><label for="id_last_name">Mobile phone:</label></p></div>
                <div class="grid-item"><p>{{ form.mobile_phone }}</p></div>
                <div class="grid-item"><p><label for="id_amka">AMKA:</label></p></div>
                <div class="grid-item"><p>{{ form.amka }}</p></div>
                <div class="grid-item"><p><label for="id_date_of_birth">Date of Birth:</label></p></div>
                <div class="grid-item" id="date-of-birth"><p>{% render_field form.date_of_birth type="date" placeholder="dd/mm/yyyy" %}</p></div>
                <div class="grid-item"><p><label for="id_notes">Notes:</label></p></div>
                <div class="grid-item"><p>{{ form.notes }}</p></div>
            </div>

        <br>
        <div id="add-form-buttons">
            <button type="submit" name="save" id="save-button">Save</button>
            <button type="submit" name="delete" id="delete-button">Delete</button>
        </div>
    </form>

{% endblock %}

dental_app/patient_management/templates/patient_management/main.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    My Dental Assistant
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'patient_management/styles.css' %}">
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
    {% csrf_token %}

    <div>
        <table id="patient-table">
            <tbody>
            <div id="main-table-title" style="margin-left: 16rem;">
                <h3>My Patients</h3>
            </div>
            <tr>
                <th id="id-header">ID</th>
                <th id="name-header">Full Name</th>
                <th id="address-header">Address</th>
                <th id="email-header">Email</th>
                <th id="phone-header">Phone</th>
                <th id="mobile-header">Mobile Phone</th>
                <th id="amka-header">AMKA</th>
                <th id="date-of-birth-header">Date of birth</th>
            </tr>
            {% for patient in filtered_patients %}
            <tr>
                <td> {{ patient.id }} </td>
                <td> <a href="{% url 'patient-details' patient_id=patient.id %}" class="row-link">{{ patient.last_name }} {{ patient.first_name }}</a></td>
                <td> {{ patient.address }} </td>
                <td> {{ patient.email }} </td>
                <td> {{ patient.phone }} </td>
                <td> {{ patient.mobile_phone }} </td>
                <td> {{ patient.amka }} </td>
                <td> {{ patient.date_of_birth }} </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% else %}

    <div class="login-promt">
        <body id="login-prompt-body">
            <form action="/login/">
                {% csrf_token %}
                <p class="login-prompt-message">You are not logged in</p>
                <button type="submit" name="login" class="btn btn-outline-primary" onclick="location.href='{% url 'login' %}'">Login</button>
            </form>
        </body>
    </div>

    {% endif %}

{% endblock %}